In [11]:
import sqlite3
import pandas as pd
conn = sqlite3.connect("all_stocks.db")

In [ ]:
#cleate tatbe　１回のみ
query = """
CREATE TABLE IF NOT EXISTS stock_master (
    ticker TEXT PRIMARY KEY,
    company_name TEXT,
    market TEXT
)
"""

conn.execute(query)
conn.commit()

In [23]:
#cleate tatbe　１回のみ
query="""
CREATE TABLE IF NOT EXISTS stock_price(
    ticker TEXT,
    date TEXT,
    open REAL,
    high REAL,
    low REAL,
    close REAL,
    volume INTEGER,
    PRIMARY KEY (ticker, date)
)
"""
conn.execute(query)
conn.commit()

In [24]:
pd.read_sql("""
SELECT *
FROM sqlite_master
WHERE type='table'
""", conn)

,type,name,tbl_name,rootpage,sql
0,table,stock_master,stock_master,2,CREATE TABLE stock_master (\n ticker TEXT P...
1,table,stock_price,stock_price,4,"CREATE TABLE stock_price(\n ticker TEXT,\n ..."

In [16]:
master_df = pd.DataFrame({
    "ticker": ["7203.T", "6758.T", "8306.T"],
    "company_name": ["トヨタ", "ソニー", "三菱UFJ"],
    "market": ["Prime", "Prime", "Prime"]
})

master_df

   ticker company_name market
0  7203.T          トヨタ  Prime
1  6758.T          ソニー  Prime
2  8306.T        三菱UFJ  Prime

In [33]:
sample_df.to_sql(
    "stock_master",   # 保存先のテーブル名
    conn,             # SQLiteへの接続（通路）
    if_exists="append",  # 既存テーブルの末尾に追加
    index=False       # pandasの左端index列は保存しない
)

# DBへの変更を確定（保存ボタン）
conn.commit()

DatabaseError: Execution failed

In [21]:
df.to_sql(
    "stock_price",
    conn,
    if_exists="append",
    index=False
)

conn.commit()

DatabaseError: Execution failed

In [ ]:
#これは使わない
#銘柄番号が連続じゃないのでエラーになる
#
sample_tickers = [f"{code}.T" for code in range(1300, 1400)]
sample_tickers = ["1301.T", "1332.T", "1333.T", "1605.T", "7203.T"]
company_names = []

for ticker in sample_tickers:
    try:
        stock = yf.Ticker(ticker)
        info = stock.info
        company_names.append(info.get("longName", "unknown"))
    except:
        company_name = "error"
        
sample_df = pd.DataFrame({
    "ticker": sample_tickers,

    "company_name": company_names,
    "market": ["Prime"] * len(sample_tickers)
})

sample_df.head()

   ticker              company_name market
0  1301.T         Kyokuyo Co., Ltd.  Prime
1  1332.T        Nissui Corporation  Prime
2  1333.T         Umios Corporation  Prime
3  1605.T         Inpex Corporation  Prime
4  7203.T  Toyota Motor Corporation  Prime

In [55]:
import sqlite3
import pandas as pd
import xlrd

master_df = pd.read_excel("data\data_j.xls")
master_df = master_df[["コード", "銘柄名", "市場・商品区分"]]
master_df.head()

master_df.to_sql("stock_master",conn,if_exists="replace",index=False)

conn.commit()


prime_df = master_df[
    master_df["市場・商品区分"].str.contains("プライム", na=False)
]

tickers = prime_df["コード"].tolist()
tickers[:5]

prime_df.head()
tickers

[1301,
 1332,
 1333,
 1375,
 1377,
 1379,
 1414,
 1417,
 1419,
 1429,
 1433,
 1515,
 1518,
 1605,
 1662,
 1663,
 '167A',
 1719,
 1720,
 1721,
 1726,
 1762,
 1766,
 1773,
 1780,
 1786,
 1801,
 1802,
 1803,
 1808,
 1812,
 1813,
 1814,
 1815,
 1820,
 1833,
 1835,
 1852,
 1860,
 1861,
 1870,
 1871,
 1873,
 1878,
 1879,
 1882,
 1885,
 1887,
 1888,
 1893,
 1898,
 1899,
 1911,
 1925,
 1926,
 1928,
 1929,
 1930,
 1934,
 1938,
 1939,
 1941,
 1942,
 1944,
 1945,
 1946,
 1949,
 1950,
 1951,
 1952,
 1959,
 1961,
 1963,
 1964,
 1968,
 1969,
 1975,
 1976,
 1979,
 1980,
 1982,
 2001,
 2002,
 2004,
 2053,
 2060,
 2108,
 2109,
 2117,
 2120,
 2121,
 2124,
 2127,
 '212A',
 2130,
 2146,
 2148,
 2153,
 2154,
 2157,
 2163,
 2168,
 2170,
 2175,
 2181,
 2198,
 2201,
 2206,
 2207,
 2209,
 2211,
 2212,
 2217,
 2220,
 2222,
 2229,
 2264,
 2266,
 2267,
 2269,
 2270,
 2281,
 2282,
 2288,
 2292,
 2294,
 2296,
 2301,
 2307,
 2317,
 2325,
 2326,
 2327,
 2331,
 2335,
 2337,
 2353,
 2359,
 2371,
 2374,
 2378,
 2379,
 2384,
 2389,
 2395,
 2410,
 2413,
 2429,
 2432,
 2433,
 2445,
 2461,
 2462,
 2471,
 2475,
 2491,
 2492,
 2501,
 2502,
 2503,
 2531,
 2533,
 2540,
 '256A',
 2579,
 2585,
 2587,
 2590,
 2593,
 25935,
 2594,
 2602,
 2607,
 2613,
 '262A',
 2659,
 2664,
 2670,
 2674,
 2676,
 2678,
 2681,
 2685,
 '268A',
 2692,
 2695,
 2726,
 2730,
 2733,
 2734,
 2737,
 2742,
 2749,
 2752,
 2753,
 2760,
 2767,
 2768,
 2784,
 2791,
 2792,
 2801,
 2802,
 2804,
 2809,
 2810,
 2811,
 2815,
 '285A',
 2871,
 2874,
 2875,
 2882,
 2884,
 2897,
 2908,
 2910,
 2914,
 2915,
 2918,
 2922,
 2929,
 2930,
 2931,
 2933,
 2935,
 2975,
 2980,
 2982,
 3002,
 3003,
 3028,
 3031,
 3034,
 3036,
 3038,
 3040,
 3046,
 3048,
 3050,
 3064,
 3076,
 3086,
 3087,
 3088,
 3091,
 3092,
 3093,
 3097,
 3099,
 3101,
 3103,
 3104,
 3105,
 3106,
 3107,
 3109,
 3110,
 3116,
 3132,
 3139,
 3148,
 3150,
 3151,
 3153,
 3154,
 3156,
 3167,
 3176,
 3179,
 3180,
 3182,
 3183,
 3186,
 3191,
 3193,
 3196,
 3197,
 3198,
 3199,
 3201,
 3221,
 3231,
 3232,
 3245,
 3252,
 3276,
 3284,
 3288,
 3289,
 3291,
 3302,
 3315,
 3333,
 3349,
 3360,
 3371,
 3382,
 3387,
 3388,
 3391,
 3393,
 3395,
 3397,
 3401,
 3402,
 3405,
 3407,
 3415,
 3431,
 3433,
 3436,
 3443,
 3445,
 3457,
 3465,
 3475,
 3480,
 3482,
 3484,
 3486,
 3496,
 3498,
 3501,
 3539,
 3543,
 3546,
 3548,
 3549,
 3561,
 3563,
 3569,
 3580,
 3591,
 3593,
 3608,
 3612,
 3626,
 3632,
 3635,
 3636,
 3649,
 3655,
 3656,
 3657,
 3659,
 3660,
 3661,
 3662,
 3663,
 3665,
 3668,
 3673,
 3676,
 3678,
 3679,
 3681,
 3687,
 '368A',
 3694,
 3696,
 3697,
 3708,
 3741,
 3762,
 3763,
 3765,
 3769,
 3771,
 3774,
 3778,
 3788,
 3817,
 3834,
 3835,
 3836,
 3837,
 3843,
 3844,
 3853,
 3854,
 3861,
 3863,
 3864,
 3865,
 3877,
 3880,
 3901,
 3902,
 3903,
 3915,
 3916,
 3921,
 3922,
 3923,
 3924,
 3925,
 3926,
 3932,
 3939,
 3941,
 3946,
 3950,
 3962,
 3963,
 3964,
 3968,
 3983,
 3984,
 3992,
 3993,
 3994,
 4004,
 4005,
 4008,
 4021,
 4022,
 4023,
 4025,
 4027,
 4028,
 4041,
 4042,
 4043,
 4044,
 4045,
 4046,
 4047,
 4051,
 4053,
 4061,
 4062,
 4063,
 4064,
 4071,
 4072,
 4078,
 4082,
 4088,
 4091,
 4092,
 4095,
 4097,
 4099,
 '409A',
 4109,
 4112,
 4114,
 4116,
 4118,
 4151,
 '417A',
 4180,
 4182,
 4183,
 4186,
 4187,
 4188,
 4189,
 4194,
 4202,
 4203,
 4204,
 4205,
 4206,
 4208,
 4212,
 4216,
 4218,
 4220,
 4221,
 4228,
 4229,
 4246,
 4249,
 4251,
 4272,
 4275,
 4290,
 '429A',
 4301,
 4307,
 4310,
 4318,
 4323,
 4324,
 4326,
 4331,
 4333,
 4337,
 4343,
 4344,
 4345,
 4362,
 4368,
 4369,
 4373,
 4384,
 4385,
 4390,
 4392,
 4396,
 4401,
 4403,
 4410,
 4413,
 4432,
 4433,
 4443,
 4446,
 4449,
 4452,
 4461,
 4462,
 4471,
 4480,
 4481,
 4483,
 4502,
 4503,
 4506,
 4507,
 4516,
 4519,
 4521,
 4523,
 4526,
 4527,
 4528,
 4530,
 4534,
 4536,
 4538,
 4540,
 4543,
 4544,
 4547,
 4548,
 4549,
 4552,
 4553,
 4554,
 4559,
 4565,
 4568,
 4569,
 4574,
 4577,
 4578,
 4587,
 4611,
 4612,
 4613,
 4617,
 4626,
 4631,
 4633,
 4634,
 4641,
 4658,
 4661,
 4662,
 4665,
 4666,
 4668,
 4674,
 4676,
 4680,
 4681,
 4684,
 4686,
 4687,
 4689,
 4694,
 4704,
 4709,
 4714,
 4718,
 4719,
 '471A',
 4722,
 4725,
 4732,
 4733,
 4743,
 4751,
 4755,
 4763,
 4765,
 4768,
 4776,
 4784,
 4792,
 4801,
 4809,
 4812,
 4813,
 4819,
 4820,
 4825,
 4826,
 4828,
 4839,
 4845,
 4847,
 4848,
 4849,
 4880,
 4886,
 4887,
 4901,
 4902,
 4911,
 4912,
 4914,
 4917,
 4919,
 4922,
 4923,
 4927,
 4928,
 4931,
 4933,
 4951,
 4956,
 4958,
 4967,
 4968,
 4971,
 4973,
 4974,
 4975,
 4980,
 4985,
 4996,
 4997,
 5011,
 5016,
 5019,
 5020,
 5021,
 5032,
 5036,
 5074,
 5076,
 50765,
 5101,
 5105,
 5108,
 5110,
 5121,
 5122,
 5142,
 5185,
 5186,
 5192,
 5195,
 5201,
 5202,
 5208,
 5214,
 5232,
 5233,
 5261,
 5262,
 5269,
 5288,
 5301,
 5302,
 5310,
 5331,
 5332,
 5333,
 5334,
 5344,
 5351,
 5352,
 5357,
 5384,
 5393,
 5401,
 5406,
 5408,
 5410,
 5411,
 5423,
 5440,
 5444,
 5445,
 5451,
 5461,
 5463,
 5471,
 5480,
 5482,
 5535,
 5541,
 5563,
 5602,
 5631,
 5632,
 5659,
 5702,
 5703,
 5706,
 5707,
 5711,
 5713,
 5714,
 5715,
 5726,
 5727,
 5741,
 5757,
 5801,
 5802,
 5803,
 5805,
 5821,
 5830,
 5831,
 5832,
 5838,
 5844,
 5851,
 5852,
 5857,
 5889,
 5901,
 5902,
 5911,
 5929,
 5930,
 5932,
 5933,
 5938,
 5943,
 5946,
 5947,
 5949,
 5957,
 5959,
 5970,
 5975,
 5976,
 5981,
 5988,
 5989,
 5991,
 6005,
 6013,
 6027,
 6035,
 6036,
 6047,
 6050,
 6055,
 6058,
 6062,
 6070,
 6071,
 6073,
 6078,
 6080,
 6088,
 6089,
 6098,
 6099,
 6101,
 6103,
 6104,
 6113,
 6118,
 6134,
 6135,
 6136,
 6140,
 6141,
 6143,
 6146,
 6151,
 6167,
 6178,
 6183,
 6184,
 6191,
 6194,
 6196,
 6197,
 6200,
 6201,
 6209,
 6222,
 6235,
 6237,
 6238,
 6240,
 6247,
 6250,
 6254,
 6258,
 6264,
 6266,
 6268,
 6269,
 6272,
 6273,
 6277,
 6278,
 6279,
 6282,
 6284,
 6287,
 6289,
 6293,
 6294,
 6298,
 6301,
 6302,
 6305,
 6306,
 6309,
 6310,
 6315,
 6323,
 6324,
 6326,
 6328,
 6330,
 6331,
 6332,
 6333,
 6339,
 6340,
 6345,
 6349,
 6351,
 6358,
 6361,
 6363,
 6364,
 6367,
 6368,
 6369,
 6370,
 6371,
 6376,
 6379,
 6381,
 6383,
 6387,
 6390,
 6395,
 6406,
 6407,
 6412,
 6413,
 6417,
 6418,
 6419,
 6420,
 6430,
 6432,
 6436,
 6440,
 6445,
 6448,
 6454,
 6455,
 6457,
 6458,
 6459,
 6460,
 6463,
 6464,
 6465,
 6471,
 6472,
 6473,
 6474,
 6479,
 6480,
 6481,
 6486,
 6490,
 6498,
 6501,
 6503,
 6504,
 6506,
 6507,
 6508,
 6516,
 6517,
 6523,
 6525,
 6526,
 6532,
 6533,
 6535,
 6539,
 6544,
 6560,
 6564,
 6571,
 6572,
 6584,
 6586,
 6588,
 6590,
 6592,
 6594,
 6615,
 6616,
 6617,
 6619,
 6620,
 6622,
 6630,
 6632,
 6638,
 6644,
 6645,
 6651,
 6652,
 6653,
 6674,
 6699,
 6701,
 6702,
 6703,
 6706,
 6707,
 6718,
 6723,
 6724,
 6727,
 6728,
 6737,
 6740,
 6741,
 6742,
 6744,
 6745,
 6750,
 6752,
 6753,
 6754,
 6758,
 6762,
 6763,
 6768,
 6770,
 6779,
 6785,
 6787,
 6788,
 6794,
 6798,
 6800,
 6804,
 6806,
 6807,
 6809,
 6810,
 6814,
 6817,
 6820,
 6823,
 6841,
 6844,
 6845,
 6849,
 6850,
 6856,
 6857,
 6859,
 6861,
 6866,
 6869,
 6871,
 6875,
 6902,
 6905,
 6908,
 6914,
 6920,
 6923,
 6925,
 6929,
 6941,
 6947,
 6951,
 6952,
 6954,
 6958,
 6961,
 6962,
 6963,
 6965,
 ...]

In [48]:
#stock_priceのリード
pd.read_sql("""
SELECT *
FROM stock_master
""", conn)

       コード                                   銘柄名       市場・商品区分
0     1301                                    極洋    プライム（内国株式）
1     1305                ｉＦｒｅｅＥＴＦ　ＴＯＰＩＸ（年１回決算型）       ETF・ETN
2     1306               ＮＥＸＴ　ＦＵＮＤＳ　ＴＯＰＩＸ連動型上場投信       ETF・ETN
3     1308                     上場インデックスファンドＴＯＰＩＸ       ETF・ETN
4     1309  ＮＥＸＴ　ＦＵＮＤＳ　ＣｈｉｎａＡＭＣ・中国株式・上証５０連動型上場投信       ETF・ETN
...    ...                                   ...           ...
4434  9991                                  ジェコス    プライム（内国株式）
4435  9993                                  ヤマザワ  スタンダード（内国株式）
4436  9994                                   やまや  スタンダード（内国株式）
4437  9996                                 サトー商会  スタンダード（内国株式）
4438  9997                                  ベルーナ    プライム（内国株式）

[4439 rows x 3 columns]

prime_df = master_df[
    master_df["market"].str.contains("プライム", na=False)
]

prime_df.head()

In [ ]:

#お試しデータ取得
import yfinance as yf
import pandas as pd
import xlrd

master_df = pd.read_excel("data\data_j.xls")
master_df = master_df[["コード", "銘柄名", "市場・商品区分"]]
master_df["コード"] = master_df["コード"].astype(str) + ".T"

prime_df = master_df[
    master_df["市場・商品区分"].str.contains("プライム", na=False)
]

tickers = prime_df["コード"].tolist()
sample_tickers = tickers[:5]#重いのでまずは
sample_tickers 


for ticker in sample_tickers:
    df = yf.download(ticker, start="2024-01-01")
    df.columns=df.columns.get_level_values(0)
    df.columns.name = None
    df["ticker"] = ticker
    df.reset_index(inplace=True)
    save_df = df[["ticker", "Date", "Open", "High", "Low", "Close", "Volume"]]
    save_df.columns = [
        "ticker",
        "date",
        "open",
        "high",
        "low",
        "close",
        "volume"
    ]
    print(save_df.head(2))

    save_df.to_sql(
        "stock_price",
        conn,
        if_exists="append",
        index=False
    )

    conn.commit()
    print("保存完了")

check_df = pd.read_sql("SELECT * FROM stock_price LIMIT 10", conn)
check_df

[*********************100%***********************]  1 of 1 completed

   ticker       date         open         high          low        close  \
0  1301.T 2024-01-04  3462.217813  3508.075002  3443.874937  3498.903564
1  1301.T 2024-01-05  3512.660786  3549.346538  3498.903629  3531.003662

   volume
0   21400
1   16800

DatabaseError: Execution failed