In [ ]:

#単純にDBに接続してカラム数をカウントしてみる
import pandas as pd
import sqlite3

conn= sqlite3.connect("all_stocks.db")
query ="select count(*) as cnt From stock_price"
pd.read_sql(query,conn)

       cnt
0  6934818

In [ ]:
import pandas as pd
import yfinance as yf

df=yf.download("7203.T",start="2025-01-01")

df.columns=df.columns.get_level_values(0)
df.columns.name = None
df.reset_index(inplace=True)
display(df.head(2))

[*********************100%***********************]  1 of 1 completed

        Date        Close         High          Low         Open    Volume
0 2025-01-06  2870.214600  2958.866196  2859.728927  2957.912953  41298500
1 2025-01-07  2909.297363  2980.790582  2854.485896  2863.541704  44700900

In [34]:
import pandas as pd
import sqlite3



conn= sqlite3.connect("all_stocks.db")
tickers="7203.T"
query = f"""SELECT MAX(date) as max_date FROM stock_price WHERE ticker='{tickers}'"""

last_date_df=pd.read_sql(query,conn)

last_date = last_date_df.loc[0, "max_date"]

if pd.isna(last_date):
    start_date = "2018-01-01"
else:
    start_date = (
    pd.to_datetime(last_date)
    + pd.Timedelta(days=1)
    ).strftime("%Y-%m-%d")


df = yf.download(
        tickers,
        start=start_date,
        progress=False
        )

if df.empty:
    print("追加データなし")

else:
    print("新規データあり")
    display(df.head())

新規データあり

Price        Close    High     Low    Open    Volume
Ticker      7203.T  7203.T  7203.T  7203.T    7203.T
Date
2026-04-13  3319.0  3337.0  3280.0  3295.0  14353200
2026-04-14  3326.0  3355.0  3288.0  3355.0  15920200
2026-04-15  3381.0  3386.0  3344.0  3355.0  20317000